language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
script: npm test
after_success:
  - npm run coveralls
env:
  - DATABASE_URL: postgres://travis@localhost:5432/travis
service:
  - postgresql
